name: GitHub Actions Demo

on: 
  push:
    branches: [ main ]
    paths-ignore: [ .github/** ]
  pull_request:
    branches: [ main ] 
  schedule:
    - cron: '15 6 * * 0'
  workflow_dispatch:
    inputs:
      enviroment:
        description: 'Environment to deploy to'
        type: environment
        required: true

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo " The job was triggered by event: ${{ github.event_name }} "
          echo " The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }} ."
      - uses: actions/checkout@v4.2.2

      - name: List files in the repository
        run: |
          echo " The repository ${{ github.repository }} contains the following files: "
          tree
  Test:
    runs-on: ubuntu-latest
    if: github.event_name == 'workflow_dispatch'
    needs: Build
    enviroment: Test
    steps:
      - run: echo " Testing... "

  Load-Test:
    runs-on: ubuntu-latest
    if: github.event_name == 'workflow_dispatch'
    needs: Build
    enviroment: Load-Test
    steps:
      - run: |
          echo " Load Testing... "
          sleep 15
  
  Production:
    runs-on: ubuntu-latest
    if: github.event_name == 'workflow_dispatch'
    needs: [Build, Test, Load-Test]
    enviroment: 
      name: Production
      url: https://github.com
    if: github.event.inputs.enviroment == 'Production'
    steps:
      - run: |
          echo " Deploying to production... "
          sleep 10
      - run: echo " The environment is ${{ github.event.inputs.enviroment }} "
      - run: echo " The job was triggered by event: ${{ github.event_name }} "
      - run: echo " The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }} ."

      
